---
- name: ELK 
  hosts: ubuntu
  pre_tasks:
  - name: Update Repository Index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
- name: ELK STACK 
  hosts: ubuntu
  roles:
    - ELK 
